server:
  port: 8085
spring:
  application:
    name: trip-service
  datasource:
    url: jdbc:postgresql://localhost:5433/trip_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
jwt:
  secret: uthao-super-secret-jwt-key-2024-extended-256bit
